# config.yml
# linked by ./dashy.nix
pageInfo:
  title: HomeBox
  description: Your Self-Hosted Services

appConfig:
  theme: colorful
  layout: auto
  iconSize: medium
  language: en

sections:
  - name: System Services
    items:
      - title: Pi-hole
        description: DNS & Ad-blocker
        icon: hl-pihole
        url: http://box.home.arpa:8080/admin/login
        statusCheck: true
      - title: Traefik
        description: Reverse Proxy
        icon: hl-traefik
        url: http://traefik.home.arpa:8081/
        statusCheck: true
  # - name: Admin Services
  #   items:
  #     - title:
  #       description:
  #       icon:
  #       url:
  #       statusCheck: true
  - name: User Services
    items:
      - title: FileBrowser
        description: server-stored file browser
        icon: hl-filebrowser
        url: http://files.home.arpa
      - title: CryptPad
        description: Office Suite
        icon: hl-cryptpad
        url: http://cryptpad.home.arpa
      - title: NextCloud Office
        description: Office Suite
        icon: hl-nextcloud
        url: http://office.home.arpa
        statusCheck: true
  # - name: Information
  #   items:
  #     - type: clock
  #       options:
  #         timeZone: America/LosAngeles
  #         format: en-US
  #         hideDate: false
  # - name: System Information
  #   items:
  #     - type: glances
  #       options:




      # - title:
      #   description:
      #   icon:
      #   url:
      #   statusCheck: true
